"""
Django settings for Lumen project.

Generated by 'django-admin startproject' using Django 3.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os
""" import environ
env = environ.Env(
    # set casting, default value
     DEBUG=(bool, False)
 )
# reading .env file
environ.Env.read_env() """
# # Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# # Quick-start development settings - unsuitable for production
# # See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# # SECURITY WARNING: keep the secret key used in production secret!

# SECRET_KEY = env('SECRET_KEY') 
SECRET_KEY='p0e5102#s=^hbp$%+=msph1d7a%98(^nq6*%#_kpz&amr3h175'

# SECURITY WARNING: don't run with debug turned on in production!
#DEBUG =env('DEBUG')
DEBUG= True

ALLOWED_HOSTS = []
#ALLOWED_HOSTS = ['192.168.1.33','192.168.1.43','127.0.0.1','[::1]']
#luego ejecutar python manage.py runserver 192.168.1.43:8000

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'Lumen.Apps.GestionBotes',
    'django_admin_listfilter_dropdown',
    'django_filters',
    'bootstrapform',

            
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Lumen.urls'

MEDIA_URL = '/DirectorioFotos/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'DirectorioFotos')
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['C:/Users/geoma/OneDrive/Lumen/Lumen/Apps/GestionBotes/Plantillas/'],
        #'DIRS': ['C:/Users/julen/OneDrive/Lumen/Lumen/Apps/GestionBotes/Plantillas/'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Lumen.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME':'postgresql_lumen', # env('POSTGRESQL_NAME'),
        'USER': 'postgres', #env('POSTGRESQL_USER'),
        'PASSWORD':'Balmaseda62', #env('POSTGRESQL_PASS'),
        'HOST':'localhost', # env('POSTGRESQL_HOST'),
        'PORT': '5432', #env('POSTGRESQL_PORT'),
        # 'ENGINE': 'django.db.backends.sqlite3',
        # 'NAME': 'Lumen.db',
        #'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'es'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/static/'
""" STATICFILES_DIRS = (os.path.join(BASE_DIR, 'static'),)
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles') """

EMAIL_BACKEND="django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST="smtp.gmail.com"

EMAIL_USE_TLS=True
EMAIL_PORT=587
EMAIL_HOST_USER="joaquin@villadiego.es"
EMAIL_HOST_PASSWORD="Arenillas62gmail"

