# Generated by Django 3.0.2 on 2020-01-23 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Botes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Equipo', models.IntegerField()),
                ('Pais', models.IntegerField()),
                ('Agno', models.IntegerField()),
                ('PrecioCompra', models.IntegerField()),
                ('PrecioVenta', models.IntegerField()),
                ('CompradoA', models.CharField(max_length=50)),
                ('FechaCompra', models.DateField()),
                ('Observaciones', models.CharField(max_length=200)),
                ('Otro', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Equipos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Paises',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Abrevation', models.CharField(max_length=2)),
                ('Nombre', models.CharField(max_length=20)),
            ],
        ),
    ]
