# Generated by Django 3.0.2 on 2020-01-24 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GestionBotes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='botes',
            name='Otro',
        ),
        migrations.AlterField(
            model_name='botes',
            name='Equipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionBotes.Equipos'),
        ),
    ]
