# Generated by Django 3.0.2 on 2020-01-25 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GestionBotes', '0002_auto_20200124_1346'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fotos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Url', models.URLField()),
                ('UbicacionLocal', models.CharField(max_length=250)),
                ('Bote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GestionBotes.Botes')),
            ],
        ),
    ]
