# Generated by Django 3.0.2 on 2020-01-26 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GestionBotes', '0003_fotos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botes',
            name='Pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionBotes.Paises'),
        ),
    ]
