# Generated by Django 3.0.2 on 2020-01-26 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionBotes', '0004_auto_20200126_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotos',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='get_image_filename'),
        ),
    ]
