# Generated by Django 3.0.2 on 2020-01-27 19:34

import Lumen.Apps.GestionBotes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionBotes', '0005_fotos_imagen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fotos',
            old_name='Bote',
            new_name='bote',
        ),
        migrations.AlterField(
            model_name='fotos',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=Lumen.Apps.GestionBotes.models.get_image_filename, verbose_name='Imagen'),
        ),
    ]
