# Generated by Django 2.2.10 on 2020-03-01 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionBotes', '0008_auto_20200223_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botes',
            name='CompradoA',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='botes',
            name='FechaCompra',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='botes',
            name='Observaciones',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='botes',
            name='PrecioCompra',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='botes',
            name='PrecioVenta',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
