# Generated by Django 2.2.10 on 2020-04-10 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionBotes', '0009_auto_20200301_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='botes',
            name='FotoPrincipal',
            field=models.ImageField(blank=True, null=True, upload_to=None, verbose_name='FotoPrincipal'),
        ),
    ]
