# Generated by Django 3.0.5 on 2020-09-23 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionBotes', '0010_botes_fotoprincipal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botes',
            name='Agno',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
