# Generated by Django 3.0.5 on 2020-09-24 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionBotes', '0011_auto_20200923_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botes',
            name='Agno',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Año'),
        ),
    ]
