# Generated by Django 3.1.2 on 2020-10-04 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GestionBotes', '0012_auto_20200924_1634'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modalidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='botes',
            name='PrecioCompra',
        ),
        migrations.AddField(
            model_name='botes',
            name='Modalidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GestionBotes.modalidad'),
        ),
    ]
